# Generated by Django 4.2.3 on 2023-07-19 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('message', models.CharField(blank=True, max_length=1024, null=True)),
                ('type', models.CharField(choices=[('SMS', 'SMS'), ('Email', 'Email')], default='Email', max_length=12)),
            ],
            options={
                'verbose_name': 'campaign',
                'verbose_name_plural': 'campaigns',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('email', models.EmailField(max_length=56, unique=True)),
                ('phone', models.CharField(max_length=56, unique=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('is_company_customer', models.BooleanField(default=False)),
                ('is_advertised_contact', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contacts',
            },
        ),
        migrations.CreateModel(
            name='CampaignSucceedMsgContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaign_management.campaign')),
                ('contacts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaign_management.contacts')),
            ],
            options={
                'verbose_name': 'campaignsucceedmsgcontact',
                'verbose_name_plural': 'campaignsucceedmsgcontacts',
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='contacts',
            field=models.ManyToManyField(related_name='campaign_contacts', to='campaign_management.contacts'),
        ),
    ]
