# Generated by Django 4.2.3 on 2023-07-20 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='city',
            new_name='address',
        ),
    ]
