# Generated by Django 3.2.7 on 2023-07-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_management', '0002_rename_city_contacts_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
