# Generated by Django 3.2.7 on 2023-07-31 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_management', '0003_contacts_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='type',
            field=models.CharField(blank=True, choices=[('SMS', 'SMS'), ('Email', 'Email')], default='Email', max_length=12, null=True),
        ),
    ]
