# Generated by Django 3.2.7 on 2023-08-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_management', '0007_auto_20230731_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='campaign_contacts', to='campaign_management.Contacts'),
        ),
    ]
