# Generated by Django 3.2.7 on 2023-08-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_management', '0008_alter_campaign_contacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='message',
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaign_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='email_body',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='email_subject',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='sms_body',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
