# Generated by Django 3.2.7 on 2023-08-04 10:03

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_management', '0009_auto_20230804_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='email_body',
            field=tinymce.models.HTMLField(default='email body'),
            preserve_default=False,
        ),
    ]
