# Generated by Django 3.2.7 on 2023-08-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_management', '0010_alter_campaign_email_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('DUE', 'DUE'), ('RUNNING', 'RUNNING'), ('SENT', 'SENT')], default='DUE', max_length=12),
        ),
    ]
