# Generated by Django 3.2.7 on 2023-08-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_management', '0012_campaign_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='clients',
            field=models.CharField(choices=[('All Clients', 'All Clients'), ('Select Clients', 'Select Clients'), ('Select Cities', 'Select Cities')], max_length=32),
        ),
    ]
