# Generated by Django 3.2.7 on 2023-08-04 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_management', '0013_alter_campaign_clients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='clients',
        ),
    ]
