# Generated by Django 3.2.7 on 2023-08-17 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_management', '0014_remove_campaign_clients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='is_company_customer',
            new_name='is_ims_contact',
        ),
    ]
