# Generated by Django 3.2.7 on 2023-08-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_management', '0016_auto_20230817_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='status',
            field=models.CharField(choices=[('FAILED', 'FAILED'), ('SUCCESS', 'SUCCESS')], default='FAILED', max_length=12),
        ),
    ]
