# Generated by Django 3.2.7 on 2023-08-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_management', '0018_alter_contacts_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(blank=True, choices=[('DUE', 'DUE'), ('RUNNING', 'RUNNING'), ('SENT', 'SENT')], default='DUE', max_length=12, null=True),
        ),
    ]
