# Generated by Django 3.2.7 on 2023-08-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_management', '0019_alter_campaign_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='status',
            field=models.CharField(blank=True, choices=[('FAILED', 'FAILED'), ('SUCCESS', 'SUCCESS')], max_length=12, null=True),
        ),
    ]
